Repository WooriFISA-Weird-Potatoes/KBOxWooriBank_Server, pull requests merged in 2023-08, with the labels that each got.

#2 [Setting] Redis 연동
  src/main/java/com/woorifisa/kboxwoori/global/config/redis/RedisConfig.java
  src/test/java/com/woorifisa/kboxwoori/global/config/redis/RedisConfigTest.java
Labels: ⚙ Setting

#4 [Setting] 크롤링 및 JWT 관련 의존성 추가
  build.gradle
Labels: ⚙ Setting

#6 [Feature] User Entity 생성
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/Club.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/Gender.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/User.java
Labels: ✨ Feature

#8 [Feature] 회원가입 구현 (Spring Security)
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserDTO.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/User.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/repository/UserRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#10 [BugFix] UserRepository 수정
  src/main/java/com/woorifisa/kboxwoori/domain/user/repository/UserRepository.java
Labels: 🐞 BugFix

#18 [Feature] 공통 응답 형식 추가
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomException.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionHandler.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
  src/main/java/com/woorifisa/kboxwoori/global/response/ResponseDto.java
Labels: ✨ Feature

#20 [Feature] 선착순 이벤트 엔티티 생성
  src/main/java/com/woorifisa/kboxwoori/domain/event/dto/EventResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/entity/Event.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/repository/EventRepository.java
Labels: ✨ Feature

#22 [Feature] 선착순 이벤트 구현
  src/main/java/com/woorifisa/kboxwoori/domain/event/controller/EventController.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/repository/EventRedisRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/repository/EventRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/service/EventService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/redis/RedisConfig.java
  src/main/resources/scripts/joinEvent.lua
  src/test/java/com/woorifisa/kboxwoori/domain/event/service/EventServiceTest.java
  src/test/java/com/woorifisa/kboxwoori/domain/event/service/JoinEventServiceTest.java
Labels: ✨ Feature

#24 [Feature] 선착순 이벤트 공통 응답 형식 적용
  src/main/java/com/woorifisa/kboxwoori/domain/event/controller/EventController.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/DuplicateParticipationException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/EventIsEndedException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/InvalidEventParticipationTimeException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/NotAuthenticatedAccoutException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/OngoingEventNotFoundException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/WooriLinkRequiredException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/repository/EventRedisRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/service/EventService.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/InternalServerErrorException.java
  src/test/java/com/woorifisa/kboxwoori/domain/event/service/EventServiceTest.java
Labels: 🔨 Refactor

#28 feat: Point내역 확인 Entity
  src/main/java/com/woorifisa/kboxwoori/domain/point/entity/Point.java
Labels: ✨ Feature

#32 [Feature] 우리은행 계정 연동 확인 구현
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
Labels: ✨ Feature

#34 [BugFix] Event Controller 예외 import 경로 수정
  src/main/java/com/woorifisa/kboxwoori/domain/event/controller/EventController.java
Labels: 🐞 BugFix

#39 [Feature] 승부예측 내역 엔티티 생성
  src/main/java/com/woorifisa/kboxwoori/domain/prediction/entity/PredictionHistory.java
  src/main/java/com/woorifisa/kboxwoori/domain/prediction/repository/PredictionHistoryRepository.java
Labels: ✨ Feature

#41 [Feature] 마이페이지 승부예측 정답률 구현
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserPageResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#43 [Feature] 검증 예외 Handler 추가
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionHandler.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
  src/main/java/com/woorifisa/kboxwoori/global/response/ResponseDto.java
Labels: ✨ Feature

#45 [Feature] UserId 중복 확인 및 유효성 검사
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/repository/UserRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionHandler.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
Labels: ✨ Feature

#47 [Feature] 경기 일정 크롤링 구현
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/dto/ScheduleDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/Schedule.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/ScheduleRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/ScheduleCrawlingService.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/ScheduleCrawlingServiceTest.java
Labels: ✨ Feature

#49 [Feature] 구단 순위 크롤링 구현
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/dto/RankingsDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/Rankings.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/RankingsRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/RankingsCrawlingService.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/RankingsCrawlingServiceTest.java
Labels: ✨ Feature

#51 [Feature] 뉴스 크롤링 구현
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/dto/NewsDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/News.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/NewsRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingService.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingServiceTest.java
Labels: ✨ Feature

#53 [Feature] 오늘 경기 일정 크롤링 구현
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/dto/TodayScheduleDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/TeamLogo.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/TodaySchedule.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/TodayScheduleRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingService.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingServiceTest.java
Labels: ✨ Feature

#55 [Feature] USER, ADMIN 인증인가
  src/main/java/com/woorifisa/kboxwoori/global/config/security/PrincipalDetails.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#59 [Feature] Quiz 구현
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/controller/QuizController.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/dto/QuizRequestDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/dto/QuizResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/dto/QuizResultResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/entity/Quiz.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/exception/AccountNotFoundException.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/exception/QuizDuplicatePartipation.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/exception/QuizEndedException.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/exception/QuizNotFoundException.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/exception/UnauthorizedException.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/repository/QuizRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizParticipantService.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizPointUpdateService.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizService.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/User.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
  src/test/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizParticipantServiceTest.java
  src/test/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizPointUpdateServiceTest.java
  src/test/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizServiceImplTest.java
Labels: ✨ Feature

#61 [Refactor] user, point관련 코드 리팩토링
  src/main/java/com/woorifisa/kboxwoori/domain/point/controller/PointController.java
  src/main/java/com/woorifisa/kboxwoori/domain/point/service/PointService.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserPageResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserSessionDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: 🔨 Refactor

#65 [Feature] 사용자 세션 redis에 저장
  build.gradle
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/User.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/redis/RedisConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#67 [Feature] 아이디, 비밀번호 제약조건 추가
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserInfoResponseDto.java
Labels: ✨ Feature

#69 [Refactor] 관리자페이지 api수정
  src/main/java/com/woorifisa/kboxwoori/domain/admin/controller/UserStatisticsController.java
Labels: 🔨 Refactor

#71 [Feature] 뉴스 크롤링 관련 예외 추가
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/News.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/exception/CrawlingDataNotFoundException.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/exception/CrawlingDataSaveException.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/exception/CrawlingStoredDataNotFoundException.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/NewsRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingServiceTest.java
Labels: ✨ Feature
