Repository WooriFISA-Weird-Potatoes/KBOxWooriBank_Server, pull requests merged in 2023-09, with the labels that each got.

#73 [Refactor] Exception 이름 변경
  src/main/java/com/woorifisa/kboxwoori/domain/point/exception/InsufficientPointsException.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
Labels: 🔨 Refactor

#75 [Refactor] UserStatisticsTest 코드 리팩토링
  src/test/java/com/woorifisa/kboxwoori/domain/admin/service/UserStatisticsServiceTest.java
Labels: 🔨 Refactor

#77 [Feature] 크롤링 Controller 구현
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/controller/CrawlingController.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/dto/ScheduleDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/dto/TodayScheduleDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/Rankings.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/Schedule.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/entity/TodaySchedule.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/RankingsRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/ScheduleRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/TodayScheduleRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/RankingsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/ScheduleCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/cors/CorsConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#83 [Feature] 선착순 이벤트 당첨자 배송지 저장 추가
  src/main/java/com/woorifisa/kboxwoori/domain/event/controller/EventController.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/entity/Winner.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/exception/WinningRecordNotFoundException.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/repository/WinnerRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/service/EventService.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserAddrResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
Labels: ✨ Feature

#86 [Refactor] 포인트 내역 테이블 필드 타입 변경
  src/main/java/com/woorifisa/kboxwoori/domain/point/dto/PointUseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/point/entity/Point.java
  src/main/java/com/woorifisa/kboxwoori/domain/point/service/PointService.java
Labels: 🔨 Refactor

#90 [BugFix] 오늘 일정 크롤링 버그 수정
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/TodayScheduleRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingService.java
Labels: 🐞 BugFix

#95 [Feature] Dockerfile 추가
  Dockerfile
Labels: ✨ Feature

#96 [Feature] JWT 인증, 인가 추가
  build.gradle
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/AuthController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/TokenDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserSessionDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/exception/InvalidUserIdPwException.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/CustomUserDetailService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/CustomUserDetails.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/CustomExceptionStatus.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/security/CustomAccessDeniedHandler.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/woorifisa/kboxwoori/global/exception/security/InvalidRefreshTokenException.java
  src/main/java/com/woorifisa/kboxwoori/global/filter/JwtFilter.java
  src/main/java/com/woorifisa/kboxwoori/global/util/JwtUtil.java
Labels: ✨ Feature

#97 [Refactor] 권한에 따른 퀴즈 API 변경
  src/main/java/com/woorifisa/kboxwoori/domain/point/dto/PointUseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/point/repository/PointRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/point/service/PointService.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/controller/QuizController.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/dto/QuizParticipationResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/dto/QuizRequestDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/dto/QuizResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/entity/Quiz.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserInfoRequestDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserLoginRequestDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/Role.java
  src/main/java/com/woorifisa/kboxwoori/global/util/AuthenticationUtil.java
Labels: 🔨 Refactor

#101 [Refactor] 알림에 퀴즈 타입 추가
  src/main/java/com/woorifisa/kboxwoori/domain/notification/entity/Notification.java
  src/main/java/com/woorifisa/kboxwoori/domain/notification/entity/Type.java
  src/main/java/com/woorifisa/kboxwoori/domain/notification/service/NotificationService.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizService.java
Labels: 🔨 Refactor

#102 [Refactor] 유저 Role Enum으로 변경
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/entity/User.java
  src/test/java/com/woorifisa/kboxwoori/domain/event/service/EventServiceTest.java
  src/test/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizServiceTest.java
Labels: 🔨 Refactor

#103 [Refactor] 크롤링 컨트롤러 api 변경
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/controller/CrawlingController.java
Labels: 🔨 Refactor

#104 [Feature] 요청을 보낸 사용자의 정보를 가져오기 위한 util 추가
  src/main/java/com/woorifisa/kboxwoori/domain/event/controller/EventController.java
  src/main/java/com/woorifisa/kboxwoori/domain/notification/controller/NotificationController.java
  src/main/java/com/woorifisa/kboxwoori/domain/point/controller/PointController.java
  src/main/java/com/woorifisa/kboxwoori/domain/prediction/controller/PredictionController.java
  src/main/java/com/woorifisa/kboxwoori/domain/prediction/service/PredictionService.java
Labels: ✨ Feature

#106 [Feature] CORS 설정
  src/main/java/com/woorifisa/kboxwoori/domain/user/service/UserService.java
  src/main/java/com/woorifisa/kboxwoori/global/config/cors/CorsConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/config/redis/RedisConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: ✨ Feature

#108 [Deploy] test 코드 실행 제외
  build.gradle
Labels: 🌏 Deploy

#110 [BugFix] 오늘 일정 크롤링 버그 수정
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/repository/TodayScheduleRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/event/controller/EventController.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingServiceTest.java
Labels: 🐞 BugFix

#112 [Feature] 알림 읽음 처리 기능 구현
  src/main/java/com/woorifisa/kboxwoori/domain/notification/controller/NotificationController.java
  src/main/java/com/woorifisa/kboxwoori/domain/notification/repository/NotificationRepository.java
  src/main/java/com/woorifisa/kboxwoori/domain/notification/service/NotificationService.java
Labels: ✨ Feature

#115 [Feature] 유저 권한 반환 api 추가
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/UserController.java
  src/main/java/com/woorifisa/kboxwoori/domain/user/dto/UserRoleResponseDto.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
  src/main/java/com/woorifisa/kboxwoori/global/util/AuthenticationUtil.java
Labels: ✨ Feature

#116 [Refactor] 크롤링 서버 분리
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/RankingsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/ScheduleCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/quiz/service/QuizService.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingServiceTest.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/RankingsCrawlingServiceTest.java
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/ScheduleCrawlingServiceTest.java
Labels: 🔨 Refactor

#118 [Bugfix] 크롤링 서버 분리로 인한 테스트 코드 수정
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingServiceTest.java
Labels: 🐞 BugFix

#120 [Deploy] application.yml 추가
  src/main/resources/application.yml
Labels: 🌏 Deploy

#122 [Deploy] cors 도메인 설정
  src/main/java/com/woorifisa/kboxwoori/domain/user/controller/MainController.java
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: 🌏 Deploy

#124 [Bugfix] 관리자용 통계 테이블 nullable 수정
  src/main/java/com/woorifisa/kboxwoori/domain/admin/controller/UserStatisticsController.java
  src/main/java/com/woorifisa/kboxwoori/domain/admin/entity/UserStatistics.java
Labels: 🐞 BugFix

#126 [Deploy] cors 도메인 추가 설정
  src/main/java/com/woorifisa/kboxwoori/global/config/security/SecurityConfig.java
Labels: 🌏 Deploy

#128 [Deploy] 무중단 배포를 위한 설정 추가
  appspec.yml
  scripts/deploy.sh
Labels: 🌏 Deploy

#130 [BugFix] 크롤링 데이터 조회 오류 수정
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/NewsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/RankingsCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/ScheduleCrawlingService.java
  src/main/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingService.java
Labels: 🐞 BugFix

#132 [BugFix] 크롤링 서버 분리로 인한 테스트 코드 제거
  src/test/java/com/woorifisa/kboxwoori/domain/crawling/service/TodayScheduleCrawlingServiceTest.java
Labels: 🐞 BugFix

#134 [Bugfix] 이벤트 참여시 오류 수정
  src/main/java/com/woorifisa/kboxwoori/domain/event/service/EventService.java
Labels: 🐞 BugFix

#136 [Bugfix] 관리자 페이지 서비스 오류 수정
  src/main/java/com/woorifisa/kboxwoori/domain/admin/service/UserStatisticsService.java
Labels: 🐞 BugFix
